/*
 * Auto-generated by make_digitalFilter/make_fft_fir_coef.py
 */

#ifndef _FFT_FIR_COEF_H_
#define _FFT_FIR_COEF_H_

#include <stdint.h>

#define FFT_FIR_MAX_N (512)
#define FFT_FIR_MAX_COMPLEX_LEN (FFT_FIR_MAX_N * 2)
#define FFT_FIR_MAX_PHASE_LEN (222)
#define FFT_FIR_MAX_INPUT (469)
#define FFT_FIR_MAX_OUTPUT (3752)

typedef struct
{
    uint32_t fs_out_hz;
    uint32_t passband_hz;
    uint32_t stopband_hz;
    uint16_t fft_len;
    uint16_t up_ratio;
    uint16_t phase_len;
    uint16_t input_len;
    uint16_t taps;
    float dc_gain;
    float gain_ratio;
    const float *h_fft;
} FFT_FIR_PROFILE;

extern const float fft_fir_h_176400_22050_u4_hp[];
extern const float fft_fir_h_176400_22050_u4_lp[];
extern const float fft_fir_h_176400_24000_u2_hp[];
extern const float fft_fir_h_176400_24000_u2_lp[];
extern const float fft_fir_h_192000_24000_u4_hp[];
extern const float fft_fir_h_192000_24000_u4_lp[];
extern const float fft_fir_h_192000_24000_u2_hp[];
extern const float fft_fir_h_192000_24000_u2_lp[];
extern const float fft_fir_h_352800_22050_u8_hp[];
extern const float fft_fir_h_352800_22050_u8_lp[];
extern const float fft_fir_h_352800_22050_u4_hp[];
extern const float fft_fir_h_352800_22050_u4_lp[];
extern const float fft_fir_h_352800_24000_u4_hp[];
extern const float fft_fir_h_352800_24000_u4_lp[];
extern const float fft_fir_h_352800_24000_u2_hp[];
extern const float fft_fir_h_352800_24000_u2_lp[];
extern const float fft_fir_h_384000_24000_u8_hp[];
extern const float fft_fir_h_384000_24000_u8_lp[];
extern const float fft_fir_h_384000_24000_u4_hp[];
extern const float fft_fir_h_384000_24000_u4_lp[];
extern const float fft_fir_h_384000_24000_u2_hp[];
extern const float fft_fir_h_384000_24000_u2_lp[];

extern const FFT_FIR_PROFILE fft_fir_profile_176400_22050_u4_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_176400_22050_u4_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_176400_24000_u2_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_176400_24000_u2_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_192000_24000_u4_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_192000_24000_u4_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_192000_24000_u2_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_192000_24000_u2_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_352800_22050_u8_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_352800_22050_u8_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_352800_22050_u4_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_352800_22050_u4_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_352800_24000_u4_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_352800_24000_u4_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_352800_24000_u2_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_352800_24000_u2_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_384000_24000_u8_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_384000_24000_u8_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_384000_24000_u4_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_384000_24000_u4_lp;
extern const FFT_FIR_PROFILE fft_fir_profile_384000_24000_u2_hp;
extern const FFT_FIR_PROFILE fft_fir_profile_384000_24000_u2_lp;

#endif
